/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package byb;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author afelr
 */
public class ByBGrafico extends javax.swing.JFrame {
    
    private ArrayList<JTextField> txt;
    private ArrayList<JTextField> txtRes;
    private ArrayList<JComboBox> cb;
    int cantRestricciones;
    int cantVariables; 


    /**
     * Creates new form ByBGrafico
     */
    public ByBGrafico() {
        initComponents();
        txt = new ArrayList<>();
        txtRes = new ArrayList<>();
        cb = new ArrayList<>();
        cmbRes.removeAllItems();
        cmbRes.addItem("min");
        cmbRes.addItem("max");
        cmbRes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRestricciones = new javax.swing.JTextPane();
        lblRestricciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVariables = new javax.swing.JTextPane();
        lblVariables = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlPanel = new javax.swing.JPanel();
        btnSolucion = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlRes = new javax.swing.JPanel();
        cmbRes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtRestricciones);

        lblRestricciones.setText("Restricciones:");

        jScrollPane1.setViewportView(txtVariables);

        lblVariables.setText("Variables:");

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(pnlPanel);

        btnSolucion.setText("Encontrar solucion");
        btnSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionActionPerformed(evt);
            }
        });

        cmbRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlResLayout = new javax.swing.GroupLayout(pnlRes);
        pnlRes.setLayout(pnlResLayout);
        pnlResLayout.setHorizontalGroup(
            pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        pnlResLayout.setVerticalGroup(
            pnlResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(pnlRes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(btnSolucion)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVariables, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblVariables)
                    .addComponent(lblRestricciones)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(btnSolucion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        cantRestricciones = Integer.parseInt(txtRestricciones.getText());
        cantVariables = Integer.parseInt(txtVariables.getText());       
        pnlRes.removeAll();
        pnlPanel.removeAll();
        generarCamposRes(cantVariables);
        pnlRes.updateUI();
        generarCampos(cantRestricciones,cantVariables);
        pnlPanel.updateUI();

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionActionPerformed

        Interprete in = new Interprete();
        
        in.interpretar(recogerDatosFunOb(), recogerDatosRes(), (String)cmbRes.getSelectedItem(), recogerDatosCB(), recogerDatosIRes(),cantVariables);
    }//GEN-LAST:event_btnSolucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ByBGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ByBGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ByBGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ByBGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ByBGrafico().setVisible(true);
            }
        });
    }

    public void generarCampos(int r, int v){
        v = (v*2)+2;
        GridLayout gl = new GridLayout(r,v);
        pnlPanel.setLayout(gl);
        for (int i = 0; i<r;i++){
            int x=1;
            for (int j = 0; j<v;j++){
                if(j%(v-2)==0 && j!=0){
                    crearComboBox();
                }else{
                    if(j%2==0 || j%(v-1)==0){
                        crearTextField();
                    }else{
                        crearLabel(x);
                        x++;
                    }
                }
            }
        }
    }
    
    public void generarCamposRes(int x){
        x=(x*2);
        GridLayout glr = new GridLayout(1,x+2);
        pnlRes.setLayout(glr);
        pnlRes.add(cmbRes);
        pnlRes.add(new JLabel("Z = "));
        int y=1;
        for (int j = 0; j<x;j++){
            if(j%2==0){
                crearTextFieldRes();
            }else{
                crearLabelRes(y);
                y++;
            }        
        }
        cmbRes.setEnabled(true);
    }
    
    public void crearTextFieldRes(){
        JTextField tfRes = new JTextField();
        pnlRes.add(tfRes);
        txtRes.add(tfRes);
    }
    
    public void crearLabelRes(int x){
        JLabel lbRes = new JLabel("X"+x);
        pnlRes.add(lbRes);
    }
    
    public void crearTextField(){
        JTextField tf = new JTextField();
        pnlPanel.add(tf);
        txt.add(tf);
    }
    
    public void crearLabel(int x){
        JLabel lb = new JLabel("X"+x);
        pnlPanel.add(lb);
    }
    
    public void crearComboBox(){
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("<=");
        comboBox.addItem(">=");
        pnlPanel.add(comboBox);
        cb.add(comboBox);
    }
    
    public ArrayList recogerDatosFunOb(){
        ArrayList<String> funcion = new ArrayList<>();
        for(JTextField f: txtRes){
            funcion.add(f.getText());
        }
        return funcion;
    }
    
    public ArrayList recogerDatosCB(){
        ArrayList<String> simbolos = new ArrayList<>();
        for(JComboBox s: cb){
            simbolos.add((String)s.getSelectedItem());
        }
        return simbolos;
    }
    
    public ArrayList recogerDatosRes(){
        ArrayList<String> restricciones = new ArrayList<>();
        for(int i = 1;i<=txt.size();i++){
            if(i%(cantVariables+1)==0&&i!=0){
                //iRestricciones.add(txt.get(i-1).getText());
            }else{
                restricciones.add(txt.get(i-1).getText());
            }
        }
        return restricciones;
    }
    
    public ArrayList recogerDatosIRes(){
        ArrayList<String> iRestricciones = new ArrayList<>();
        for(int i = 1;i<=txt.size();i++){
            if(i%(cantVariables+1)==0&&i!=0){
                iRestricciones.add(txt.get(i-1).getText());
            }
        }
        return iRestricciones;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnSolucion;
    private javax.swing.JComboBox<String> cmbRes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblRestricciones;
    private javax.swing.JLabel lblVariables;
    private javax.swing.JPanel pnlPanel;
    private javax.swing.JPanel pnlRes;
    private javax.swing.JTextPane txtRestricciones;
    private javax.swing.JTextPane txtVariables;
    // End of variables declaration//GEN-END:variables
}
